spring:
  config:
    import: optional:classpath:sqlite.properties
  kafka:
    bootstrap-servers: kafka-service:9092
    consumer:
      group-id: product-inventory-group
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

order:
  service:
    url: http://order-api-service:80
    #url: http://localhost:5206

logging:
  file:
    name: logs/app.log
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com.catalog: INFO
    org.springframework: WARN
    org.hibernate: WARN
    org.apache.kafka: WARN
    com.zaxxer.hikari: WARN